spring:
  application:
    name: resolvetech

  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret: RGVzYXJyb2xsb19BcGxpY2FjaW9uZXNfV2ViXzIwMjY=
    expiration: 3600000

server:
  port: 8080
